// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PetMinder.Data;

#nullable disable

namespace WebApplication1.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250620003144_ChangedPetsRequiredInfoo")]
    partial class ChangedPetsRequiredInfoo
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "booking_status", new[] { "pending", "accepted", "rejected", "cancelled" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "cancellation_policy_name", new[] { "standard", "late" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "cancelled_by", new[] { "owner", "sitter" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "change_requested_by", new[] { "owner", "sitter" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "notification_type", new[] { "booking_request", "booking_accepted", "booking_rejected", "booking_cancelled", "change_requested", "change_accepted", "change_rejected", "system_alert" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "point_policy_service_type", new[] { "pet", "house" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "transaction_type", new[] { "booking", "donation", "adjustment" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "user_role", new[] { "none", "basic_user", "owner", "sitter", "admin" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "verification_status_name", new[] { "unverified", "basic", "verified", "home_verified" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PetMinder.Models.Badge", b =>
                {
                    b.Property<long>("BadgeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("BadgeId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsSpendable")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("BadgeId");

                    b.ToTable("Badges");
                });

            modelBuilder.Entity("PetMinder.Models.BookingCancellation", b =>
                {
                    b.Property<long>("CancellationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("CancellationId"));

                    b.Property<long>("BookingId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CancelledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CancelledBy")
                        .HasColumnType("integer");

                    b.Property<long>("PolicyId")
                        .HasColumnType("bigint");

                    b.HasKey("CancellationId");

                    b.HasIndex("BookingId")
                        .IsUnique();

                    b.HasIndex("PolicyId");

                    b.ToTable("BookingCancellations");
                });

            modelBuilder.Entity("PetMinder.Models.BookingChange", b =>
                {
                    b.Property<long>("ChangeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ChangeId"));

                    b.Property<long>("BookingId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ProposedEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ProposedStart")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RequestedBy")
                        .HasColumnType("integer");

                    b.HasKey("ChangeId");

                    b.HasIndex("BookingId");

                    b.ToTable("BookingChanges");
                });

            modelBuilder.Entity("PetMinder.Models.BookingRequest", b =>
                {
                    b.Property<long>("BookingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("BookingId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("OfferedPoints")
                        .HasColumnType("integer");

                    b.Property<long>("OwnerId")
                        .HasColumnType("bigint");

                    b.Property<long>("PetId")
                        .HasColumnType("bigint");

                    b.Property<long>("SitterId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("BookingId");

                    b.HasIndex("OwnerId");

                    b.HasIndex("PetId");

                    b.HasIndex("SitterId");

                    b.ToTable("BookingRequests");
                });

            modelBuilder.Entity("PetMinder.Models.CancellationPolicy", b =>
                {
                    b.Property<long>("PolicyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("PolicyId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Name")
                        .HasColumnType("integer");

                    b.Property<int>("RefundPercentage")
                        .HasColumnType("integer");

                    b.HasKey("PolicyId");

                    b.ToTable("CancellationPolicies");
                });

            modelBuilder.Entity("PetMinder.Models.Conversation", b =>
                {
                    b.Property<long>("ConversationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ConversationId"));

                    b.Property<long?>("BookingId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ConversationId");

                    b.HasIndex("BookingId")
                        .IsUnique();

                    b.ToTable("Conversations");
                });

            modelBuilder.Entity("PetMinder.Models.ConversationParticipant", b =>
                {
                    b.Property<long>("ParticipantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ParticipantId"));

                    b.Property<long>("ConversationId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("ParticipantId");

                    b.HasIndex("UserId");

                    b.HasIndex("ConversationId", "UserId")
                        .IsUnique();

                    b.ToTable("ConversationParticipants");
                });

            modelBuilder.Entity("PetMinder.Models.DeviceFingerprint", b =>
                {
                    b.Property<long>("FingerprintId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("FingerprintId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Fingerprint")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("FingerprintId");

                    b.HasIndex("UserId");

                    b.ToTable("DeviceFingerprints");
                });

            modelBuilder.Entity("PetMinder.Models.HouseIssueReport", b =>
                {
                    b.Property<long>("IssueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("IssueId"));

                    b.Property<long>("BookingId")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long?>("HouseListingListingId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("ReportedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("ReporterId")
                        .HasColumnType("bigint");

                    b.HasKey("IssueId");

                    b.HasIndex("BookingId");

                    b.HasIndex("HouseListingListingId");

                    b.HasIndex("ReporterId");

                    b.ToTable("HouseIssueReports");
                });

            modelBuilder.Entity("PetMinder.Models.HouseListing", b =>
                {
                    b.Property<long>("ListingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ListingId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("OwnerId")
                        .HasColumnType("bigint");

                    b.HasKey("ListingId");

                    b.HasIndex("OwnerId");

                    b.ToTable("HouseListings");
                });

            modelBuilder.Entity("PetMinder.Models.HousePhoto", b =>
                {
                    b.Property<long>("PhotoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("PhotoId"));

                    b.Property<long>("ListingId")
                        .HasColumnType("bigint");

                    b.Property<string>("PhotoUrl")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("PhotoId");

                    b.HasIndex("ListingId");

                    b.ToTable("HousePhotos");
                });

            modelBuilder.Entity("PetMinder.Models.Message", b =>
                {
                    b.Property<long>("MessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("MessageId"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("ConversationId")
                        .HasColumnType("bigint");

                    b.Property<long>("SenderId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("MessageId");

                    b.HasIndex("ConversationId");

                    b.HasIndex("SenderId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("PetMinder.Models.Notification", b =>
                {
                    b.Property<long>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("NotificationId"));

                    b.Property<long?>("BookingId")
                        .HasColumnType("bigint");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("MessageId")
                        .HasColumnType("bigint");

                    b.Property<int>("NotificationType")
                        .HasColumnType("integer");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("NotificationId");

                    b.HasIndex("BookingId");

                    b.HasIndex("MessageId");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("PetMinder.Models.Pet", b =>
                {
                    b.Property<long>("PetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("PetId"));

                    b.Property<int>("Age")
                        .HasColumnType("integer");

                    b.Property<string>("BehaviorNotes")
                        .HasColumnType("text");

                    b.Property<string>("Breed")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("HealthNotes")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("PetId");

                    b.HasIndex("UserId");

                    b.ToTable("Pets");
                });

            modelBuilder.Entity("PetMinder.Models.PointDonation", b =>
                {
                    b.Property<long>("DonationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("DonationId"));

                    b.Property<long>("PointsTransactionId")
                        .HasColumnType("bigint");

                    b.Property<long>("ShelterId")
                        .HasColumnType("bigint");

                    b.HasKey("DonationId");

                    b.HasIndex("PointsTransactionId")
                        .IsUnique();

                    b.HasIndex("ShelterId");

                    b.ToTable("PointDonations");
                });

            modelBuilder.Entity("PetMinder.Models.PointPolicy", b =>
                {
                    b.Property<long>("PolicyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("PolicyId"));

                    b.Property<int>("ExpiryDays")
                        .HasColumnType("integer");

                    b.Property<int>("MinSpendable")
                        .HasColumnType("integer");

                    b.Property<int>("PointsPerStay")
                        .HasColumnType("integer");

                    b.Property<int>("ServiceType")
                        .HasMaxLength(20)
                        .HasColumnType("integer");

                    b.HasKey("PolicyId");

                    b.ToTable("PointPolicies");
                });

            modelBuilder.Entity("PetMinder.Models.PointsTransaction", b =>
                {
                    b.Property<long>("TrasactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("TrasactionId"));

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Points")
                        .HasColumnType("integer");

                    b.Property<long>("PolicyId")
                        .HasColumnType("bigint");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("ReceiverId")
                        .HasColumnType("bigint");

                    b.Property<long>("SenderId")
                        .HasColumnType("bigint");

                    b.Property<int>("TransactionType")
                        .HasColumnType("integer");

                    b.HasKey("TrasactionId");

                    b.HasIndex("PolicyId");

                    b.HasIndex("ReceiverId");

                    b.HasIndex("SenderId");

                    b.ToTable("PointsTransactions");
                });

            modelBuilder.Entity("PetMinder.Models.QualificationType", b =>
                {
                    b.Property<long>("QualificationTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("QualificationTypeId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("QualificationTypeId");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("QualificationTypes");
                });

            modelBuilder.Entity("PetMinder.Models.RestrictionType", b =>
                {
                    b.Property<long>("RestrictionTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("RestrictionTypeId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("RestrictionTypeId");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("RestrictionTypes");
                });

            modelBuilder.Entity("PetMinder.Models.Review", b =>
                {
                    b.Property<long>("ReviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ReviewId"));

                    b.Property<long>("BookingId")
                        .HasColumnType("bigint");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("HouseRating")
                        .HasColumnType("integer");

                    b.Property<int?>("OwnerRating")
                        .HasColumnType("integer");

                    b.Property<long?>("PetId")
                        .HasColumnType("bigint");

                    b.Property<int?>("PetRating")
                        .HasColumnType("integer");

                    b.Property<long>("RevieweeId")
                        .HasColumnType("bigint");

                    b.Property<long>("ReviewerId")
                        .HasColumnType("bigint");

                    b.Property<int?>("SitterRating")
                        .HasColumnType("integer");

                    b.HasKey("ReviewId");

                    b.HasIndex("BookingId");

                    b.HasIndex("PetId");

                    b.HasIndex("RevieweeId");

                    b.HasIndex("ReviewerId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("PetMinder.Models.ReviewReport", b =>
                {
                    b.Property<long>("ReportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ReportId"));

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("ReportedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("ReporterId")
                        .HasColumnType("bigint");

                    b.Property<long>("ReviewId")
                        .HasColumnType("bigint");

                    b.HasKey("ReportId");

                    b.HasIndex("ReporterId");

                    b.HasIndex("ReviewId");

                    b.ToTable("ReviewReports");
                });

            modelBuilder.Entity("PetMinder.Models.Shelter", b =>
                {
                    b.Property<long>("ShelterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ShelterId"));

                    b.Property<string>("ContactInfo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("ShelterId");

                    b.ToTable("Shelters");
                });

            modelBuilder.Entity("PetMinder.Models.SitterAvailability", b =>
                {
                    b.Property<long>("AvailabilityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("AvailabilityId"));

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("SitterId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("AvailabilityId");

                    b.HasIndex("SitterId");

                    b.ToTable("SitterAvailabilities");
                });

            modelBuilder.Entity("PetMinder.Models.SitterQualification", b =>
                {
                    b.Property<long>("SitterQualificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("SitterQualificationId"));

                    b.Property<DateTime>("GrantedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("QualificationTypeId")
                        .HasColumnType("bigint");

                    b.Property<long>("SitterId")
                        .HasColumnType("bigint");

                    b.HasKey("SitterQualificationId");

                    b.HasIndex("QualificationTypeId");

                    b.HasIndex("SitterId", "QualificationTypeId")
                        .IsUnique();

                    b.ToTable("SitterQualifications");
                });

            modelBuilder.Entity("PetMinder.Models.SitterRestriction", b =>
                {
                    b.Property<long>("SitterRestrictionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("SitterRestrictionId"));

                    b.Property<long>("RestrictionTypeId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("SetAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("SitterId")
                        .HasColumnType("bigint");

                    b.HasKey("SitterRestrictionId");

                    b.HasIndex("RestrictionTypeId");

                    b.HasIndex("SitterId", "RestrictionTypeId")
                        .IsUnique();

                    b.ToTable("SitterRestrictions");
                });

            modelBuilder.Entity("PetMinder.Models.SitterSettings", b =>
                {
                    b.Property<long>("SitterId")
                        .HasColumnType("bigint");

                    b.Property<int>("MinPoints")
                        .HasColumnType("integer");

                    b.HasKey("SitterId");

                    b.ToTable("SitterSettings");
                });

            modelBuilder.Entity("PetMinder.Models.User", b =>
                {
                    b.Property<long>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)");

                    b.Property<string>("ProfilePhotoUrl")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Phone")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("PetMinder.Models.UserBadge", b =>
                {
                    b.Property<long>("UserBadgeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("UserBadgeId"));

                    b.Property<DateTime>("AwardedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("BadgeId")
                        .HasColumnType("bigint");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("UserBadgeId");

                    b.HasIndex("BadgeId");

                    b.HasIndex("UserId", "BadgeId")
                        .IsUnique();

                    b.ToTable("UserBadges");
                });

            modelBuilder.Entity("PetMinder.Models.UserVerification", b =>
                {
                    b.Property<long>("UserVerificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("UserVerificationId"));

                    b.Property<string>("DocumentUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<long>("VerificationStatusId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("VerifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserVerificationId");

                    b.HasIndex("UserId");

                    b.HasIndex("VerificationStatusId");

                    b.ToTable("UserVerifications");
                });

            modelBuilder.Entity("PetMinder.Models.VerificationStatus", b =>
                {
                    b.Property<long>("VerificationStatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("VerificationStatusId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Name")
                        .HasColumnType("integer");

                    b.HasKey("VerificationStatusId");

                    b.ToTable("VerificationStatuses");
                });

            modelBuilder.Entity("PetMinder.Models.BookingCancellation", b =>
                {
                    b.HasOne("PetMinder.Models.BookingRequest", "BookingRequest")
                        .WithOne("Cancellation")
                        .HasForeignKey("PetMinder.Models.BookingCancellation", "BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PetMinder.Models.CancellationPolicy", "CancellationPolicy")
                        .WithMany("Cancellations")
                        .HasForeignKey("PolicyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BookingRequest");

                    b.Navigation("CancellationPolicy");
                });

            modelBuilder.Entity("PetMinder.Models.BookingChange", b =>
                {
                    b.HasOne("PetMinder.Models.BookingRequest", "BookingRequest")
                        .WithMany("BookingChanges")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BookingRequest");
                });

            modelBuilder.Entity("PetMinder.Models.BookingRequest", b =>
                {
                    b.HasOne("PetMinder.Models.User", "Owner")
                        .WithMany("OwnedBookings")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PetMinder.Models.Pet", "Pet")
                        .WithMany("BookingRequests")
                        .HasForeignKey("PetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PetMinder.Models.User", "Sitter")
                        .WithMany("SittingBookings")
                        .HasForeignKey("SitterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Owner");

                    b.Navigation("Pet");

                    b.Navigation("Sitter");
                });

            modelBuilder.Entity("PetMinder.Models.Conversation", b =>
                {
                    b.HasOne("PetMinder.Models.BookingRequest", "BookingRequest")
                        .WithOne("Conversation")
                        .HasForeignKey("PetMinder.Models.Conversation", "BookingId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("BookingRequest");
                });

            modelBuilder.Entity("PetMinder.Models.ConversationParticipant", b =>
                {
                    b.HasOne("PetMinder.Models.Conversation", "Conversation")
                        .WithMany("Participants")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PetMinder.Models.User", "User")
                        .WithMany("ConversationParticipations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conversation");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PetMinder.Models.DeviceFingerprint", b =>
                {
                    b.HasOne("PetMinder.Models.User", "User")
                        .WithMany("DeviceFingerprints")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("PetMinder.Models.HouseIssueReport", b =>
                {
                    b.HasOne("PetMinder.Models.BookingRequest", "BookingRequest")
                        .WithMany("HouseIssues")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PetMinder.Models.HouseListing", null)
                        .WithMany("IssueReports")
                        .HasForeignKey("HouseListingListingId");

                    b.HasOne("PetMinder.Models.User", "Reporter")
                        .WithMany("HouseIssueReports")
                        .HasForeignKey("ReporterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BookingRequest");

                    b.Navigation("Reporter");
                });

            modelBuilder.Entity("PetMinder.Models.HouseListing", b =>
                {
                    b.HasOne("PetMinder.Models.User", "Owner")
                        .WithMany("HouseListings")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("PetMinder.Models.CheckList", "CheckList", b1 =>
                        {
                            b1.Property<long>("HouseListingListingId")
                                .HasColumnType("bigint");

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<int>("Floor")
                                .HasColumnType("integer");

                            b1.Property<int>("NumberofRooms")
                                .HasColumnType("integer");

                            b1.Property<int>("SizeofHome")
                                .HasColumnType("integer");

                            b1.Property<bool>("hasElevator")
                                .HasColumnType("boolean");

                            b1.Property<bool>("hasWifi")
                                .HasColumnType("boolean");

                            b1.HasKey("HouseListingListingId");

                            b1.ToTable("HouseListings");

                            b1.WithOwner()
                                .HasForeignKey("HouseListingListingId");
                        });

                    b.Navigation("CheckList")
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("PetMinder.Models.HousePhoto", b =>
                {
                    b.HasOne("PetMinder.Models.HouseListing", "Listing")
                        .WithMany("Photos")
                        .HasForeignKey("ListingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Listing");
                });

            modelBuilder.Entity("PetMinder.Models.Message", b =>
                {
                    b.HasOne("PetMinder.Models.Conversation", "Conversation")
                        .WithMany("Messages")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PetMinder.Models.User", "Sender")
                        .WithMany("MessagesSent")
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Conversation");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("PetMinder.Models.Notification", b =>
                {
                    b.HasOne("PetMinder.Models.BookingRequest", "BookingRequest")
                        .WithMany("Notifications")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("PetMinder.Models.Message", "Message")
                        .WithMany("Notifications")
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("PetMinder.Models.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BookingRequest");

                    b.Navigation("Message");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PetMinder.Models.Pet", b =>
                {
                    b.HasOne("PetMinder.Models.User", "Owner")
                        .WithMany("Pets")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("PetMinder.Models.PointDonation", b =>
                {
                    b.HasOne("PetMinder.Models.PointsTransaction", "PointsTransaction")
                        .WithOne("PointDonation")
                        .HasForeignKey("PetMinder.Models.PointDonation", "PointsTransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PetMinder.Models.Shelter", "Shelter")
                        .WithMany("PointDonations")
                        .HasForeignKey("ShelterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PointsTransaction");

                    b.Navigation("Shelter");
                });

            modelBuilder.Entity("PetMinder.Models.PointsTransaction", b =>
                {
                    b.HasOne("PetMinder.Models.PointPolicy", "PointPolicy")
                        .WithMany("Transactions")
                        .HasForeignKey("PolicyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PetMinder.Models.User", "Receiver")
                        .WithMany("TransactionsReceived")
                        .HasForeignKey("ReceiverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PetMinder.Models.User", "Sender")
                        .WithMany("TransactionsSent")
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PointPolicy");

                    b.Navigation("Receiver");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("PetMinder.Models.Review", b =>
                {
                    b.HasOne("PetMinder.Models.BookingRequest", "Booking")
                        .WithMany("Reviews")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PetMinder.Models.Pet", "Pet")
                        .WithMany("PetReviews")
                        .HasForeignKey("PetId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PetMinder.Models.User", "Reviewee")
                        .WithMany("ReviewsReceived")
                        .HasForeignKey("RevieweeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PetMinder.Models.User", "Reviewer")
                        .WithMany("ReviewsWritten")
                        .HasForeignKey("ReviewerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Booking");

                    b.Navigation("Pet");

                    b.Navigation("Reviewee");

                    b.Navigation("Reviewer");
                });

            modelBuilder.Entity("PetMinder.Models.ReviewReport", b =>
                {
                    b.HasOne("PetMinder.Models.User", "Reporter")
                        .WithMany("ReviewReportsMade")
                        .HasForeignKey("ReporterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PetMinder.Models.Review", "Review")
                        .WithMany("ReviewReports")
                        .HasForeignKey("ReviewId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reporter");

                    b.Navigation("Review");
                });

            modelBuilder.Entity("PetMinder.Models.SitterAvailability", b =>
                {
                    b.HasOne("PetMinder.Models.User", "Sitter")
                        .WithMany("Availabilities")
                        .HasForeignKey("SitterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sitter");
                });

            modelBuilder.Entity("PetMinder.Models.SitterQualification", b =>
                {
                    b.HasOne("PetMinder.Models.QualificationType", "QualificationType")
                        .WithMany("SitterQualifications")
                        .HasForeignKey("QualificationTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PetMinder.Models.User", "Sitter")
                        .WithMany("SitterQualifications")
                        .HasForeignKey("SitterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("QualificationType");

                    b.Navigation("Sitter");
                });

            modelBuilder.Entity("PetMinder.Models.SitterRestriction", b =>
                {
                    b.HasOne("PetMinder.Models.RestrictionType", "RestrictionType")
                        .WithMany("SitterRestrictions")
                        .HasForeignKey("RestrictionTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PetMinder.Models.User", "Sitter")
                        .WithMany("SitterRestrictions")
                        .HasForeignKey("SitterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RestrictionType");

                    b.Navigation("Sitter");
                });

            modelBuilder.Entity("PetMinder.Models.SitterSettings", b =>
                {
                    b.HasOne("PetMinder.Models.User", "User")
                        .WithOne("SitterSettings")
                        .HasForeignKey("PetMinder.Models.SitterSettings", "SitterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("PetMinder.Models.UserBadge", b =>
                {
                    b.HasOne("PetMinder.Models.Badge", "Badge")
                        .WithMany("UserBadges")
                        .HasForeignKey("BadgeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PetMinder.Models.User", "User")
                        .WithMany("Badges")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Badge");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PetMinder.Models.UserVerification", b =>
                {
                    b.HasOne("PetMinder.Models.User", "User")
                        .WithMany("Verifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PetMinder.Models.VerificationStatus", "VerificationStatus")
                        .WithMany("UserVerifications")
                        .HasForeignKey("VerificationStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("VerificationStatus");
                });

            modelBuilder.Entity("PetMinder.Models.Badge", b =>
                {
                    b.Navigation("UserBadges");
                });

            modelBuilder.Entity("PetMinder.Models.BookingRequest", b =>
                {
                    b.Navigation("BookingChanges");

                    b.Navigation("Cancellation")
                        .IsRequired();

                    b.Navigation("Conversation")
                        .IsRequired();

                    b.Navigation("HouseIssues");

                    b.Navigation("Notifications");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("PetMinder.Models.CancellationPolicy", b =>
                {
                    b.Navigation("Cancellations");
                });

            modelBuilder.Entity("PetMinder.Models.Conversation", b =>
                {
                    b.Navigation("Messages");

                    b.Navigation("Participants");
                });

            modelBuilder.Entity("PetMinder.Models.HouseListing", b =>
                {
                    b.Navigation("IssueReports");

                    b.Navigation("Photos");
                });

            modelBuilder.Entity("PetMinder.Models.Message", b =>
                {
                    b.Navigation("Notifications");
                });

            modelBuilder.Entity("PetMinder.Models.Pet", b =>
                {
                    b.Navigation("BookingRequests");

                    b.Navigation("PetReviews");
                });

            modelBuilder.Entity("PetMinder.Models.PointPolicy", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("PetMinder.Models.PointsTransaction", b =>
                {
                    b.Navigation("PointDonation")
                        .IsRequired();
                });

            modelBuilder.Entity("PetMinder.Models.QualificationType", b =>
                {
                    b.Navigation("SitterQualifications");
                });

            modelBuilder.Entity("PetMinder.Models.RestrictionType", b =>
                {
                    b.Navigation("SitterRestrictions");
                });

            modelBuilder.Entity("PetMinder.Models.Review", b =>
                {
                    b.Navigation("ReviewReports");
                });

            modelBuilder.Entity("PetMinder.Models.Shelter", b =>
                {
                    b.Navigation("PointDonations");
                });

            modelBuilder.Entity("PetMinder.Models.User", b =>
                {
                    b.Navigation("Availabilities");

                    b.Navigation("Badges");

                    b.Navigation("ConversationParticipations");

                    b.Navigation("DeviceFingerprints");

                    b.Navigation("HouseIssueReports");

                    b.Navigation("HouseListings");

                    b.Navigation("MessagesSent");

                    b.Navigation("Notifications");

                    b.Navigation("OwnedBookings");

                    b.Navigation("Pets");

                    b.Navigation("ReviewReportsMade");

                    b.Navigation("ReviewsReceived");

                    b.Navigation("ReviewsWritten");

                    b.Navigation("SitterQualifications");

                    b.Navigation("SitterRestrictions");

                    b.Navigation("SitterSettings")
                        .IsRequired();

                    b.Navigation("SittingBookings");

                    b.Navigation("TransactionsReceived");

                    b.Navigation("TransactionsSent");

                    b.Navigation("Verifications");
                });

            modelBuilder.Entity("PetMinder.Models.VerificationStatus", b =>
                {
                    b.Navigation("UserVerifications");
                });
#pragma warning restore 612, 618
        }
    }
}
